name: pizza_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  cart_repository:
    path: packages/cart_repository
  payment_repository:
    path: packages/payment_repository
    # Thêm dependencies cho VNPAY
  url_launcher: ^6.2.2
  crypto: ^3.0.3
  uuid: ^4.2.1
  app_links: ^6.3.2
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
