name: cart_repository
description: A cart repository for managing cart data with Firebase.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  equatable: ^2.0.7
  pizza_repository:
    path: ../pizza_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
